// Conversation.js (Model for Conversations)

const admin = require('firebase-admin');

const conversationSchema = {
  conversationId: "unique-conversation-id",  // Automatically generated by Firestore
  participants: ["user1-id", "user2-id"],    // Array of participants (for direct, group, or channel conversations)
  type: "direct" || "group" || "channel",    // Type of conversation
  participantCount: 2,                       // Number of participants in the conversation
  conversationName: "Group Chat",            // Name of the conversation (optional)
  pinnedMessages: ["message1-id"],           // Array of pinned message IDs
  profilePhotoURL: "path/to/photo.png",      // URL or path to the conversation's profile photo (optional)
  createdAt: new Date(),                     // Timestamp when conversation was created
  updatedAt: new Date(),                     // Timestamp when conversation was last updated
  owner: "owner-user-id",                   // Owner of the conversation (only one)
  admins: ["admin-user-id"],                // Array of admins for group chats/channels
  permissions: {                             // Permissions schema for customization
    addParticipants: true,                   // Whether participants can be added
    removeParticipants: true,                // Whether participants can be removed
    renameConversation: true,                // Whether the conversation can be renamed
    pinMessages: true,                       // Whether messages can be pinned
    clearMessages: true                      // Whether messages can be cleared
  }
};

module.exports = conversationSchema;

// Example of Direct Conversation
const directConversation = {
  conversationId: "abc123",
  participants: ["user1-id", "user2-id"],  // Two participants for a direct conversation
  type: "direct",                         // Type: direct conversation
  participantCount: 2,                    // Number of participants in this conversation
  conversationName: null,                 // Direct chats may not have a conversation name
  pinnedMessages: [],                     // No pinned messages in direct chat
  profilePhotoURL: null,                  // No profile photo for direct chats
  createdAt: "2024-01-01T12:00:00Z",
  updatedAt: "2024-01-01T12:30:00Z",
  owner: "user1-id",                    // Owner of the conversation
  admins: [],                             // No admins in direct conversations
  permissions: {                          // Permissions for direct conversations
    addParticipants: false,
    removeParticipants: false,
    renameConversation: false,
    pinMessages: false,
    clearMessages: false
  }
};

// Example of Group Chat
const groupConversation = {
  conversationId: "group789",
  participants: ["user1-id", "user2-id", "user3-id"],  // Multiple participants
  type: "group",                                       // Type: group chat
  participantCount: 3,                                 // Number of participants
  conversationName: "Friends Group",                   // Name of the group chat
  pinnedMessages: ["message1-id"],                     // Pinned message IDs
  profilePhotoURL: "https://example.com/path-to-photo.jpg", // URL to the profile photo
  createdAt: "2024-01-01T12:00:00Z",
  updatedAt: "2024-01-01T12:30:00Z",
  owner: "user1-id",                                  // Owner of the group
  admins: ["user2-id"],                               // Admins for the group
  permissions: {                                        // Permissions for group chat
    addParticipants: true,
    removeParticipants: true,
    renameConversation: true,
    pinMessages: true,
    clearMessages: true
  }
};

// Example of Channel
const channelConversation = {
  conversationId: "channel456",
  participants: ["user1-id", "user2-id", "user3-id"],  // Multiple participants
  type: "channel",                                    // Type: channel
  participantCount: 3,                                // Number of participants
  conversationName: "General Channel",                // Name of the channel
  pinnedMessages: [],                                 // No pinned messages by default
  profilePhotoURL: "https://example.com/path-to-channel-photo.jpg", // URL to the channel profile photo
  createdAt: "2024-01-01T12:00:00Z",
  updatedAt: "2024-01-01T12:30:00Z",
  owner: "user1-id",                                 // Owner of the channel
  admins: ["admin-user-id"],                         // Admins who control the channel
  permissions: {                                       // Permissions for the channel
    addParticipants: true,
    removeParticipants: true,
    renameConversation: true,
    pinMessages: true,
    clearMessages: true
  }
};

// Function to create a conversation document in Firestore
async function createConversation(participants, type, owner, admins = [], permissions = {}, conversationName = null, profilePhotoURL = null) {
  const conversationData = {
    participants,
    type,
    participantCount: participants.length,   // Store the number of participants
    conversationName,                        // Optional conversation name
    profilePhotoURL,                         // Optional profile photo URL
    pinnedMessages: [],                      // Initialize with no pinned messages
    createdAt: new Date(),
    updatedAt: new Date(),
    owner,                                   // Owner of the conversation
    admins,                                  // Admins, if any
    permissions                              // Permissions for admins and participants
  };

  const newConversation = await admin.firestore().collection('conversations').add(conversationData);
  return newConversation.id;
}

module.exports = { conversationSchema, createConversation };