// Firestore Structure for Messages
const messageSchema = {
  messageId: "unique-message-id",             // Automatically generated by Firestore
  conversationId: "unique-conversation-id",   // Reference to the conversation this message belongs to
  senderId: "user-id",                        // ID of the user who sent the message
  content: "encrypted-message-content",       // Encrypted message content
  timestamp: new Date()                       // Timestamp when message was sent
};

module.exports = messageSchema;

// Example of a Message in a Direct Conversation
const directMessage = {
  messageId: "msg123",
  conversationId: "abc123",                  // The direct conversation this message belongs to
  senderId: "user1-id",                      // Sender's ID
  content: "encrypted-hello-world",          // Encrypted message content
  timestamp: "2024-01-01T12:30:00Z"          // When the message was sent
};

// Example of a Message in a Group Chat
const groupMessage = {
  messageId: "msg789",
  conversationId: "group789",                // The group conversation this message belongs to
  senderId: "user2-id",                      // Sender's ID
  content: "encrypted-group-message",        // Encrypted group message content
  timestamp: "2024-01-01T12:45:00Z"          // When the message was sent
};
